"""Service layer modules for Jarvis Brain."""

from .search_service import search_web, summarise_search_results
from .email_service import (
    fetch_unread_summary,
    write_email_summary,
    build_markdown,
    build_email_markdown,
    search_messages_in_window,
    mark_messages_read,
    mark_messages_read_action,
    mark_messages_unread,
    archive_messages,
    delete_messages,
    apply_label,
    send_email,
    mark_inbox_unread,
    search_messages_by_criteria,
    fetch_full_message,
    send_reply,
)
from .calendar_service import (
    get_today_agenda,
    get_tomorrow_agenda,
    get_next_important_event,
    get_events_between,
    write_calendar_briefing,
    build_daily_markdown,
    create_event,
    update_event,
    delete_event,
)
from .tasks_service import (
    list_tasks,
    create_task,
    update_task,
    complete_task,
    delete_task,
)
from .docs_service import (
    append_to_doc,
    create_doc,
    fetch_document,
    render_document_text,
    search_docs,
)
from .sheets_service import create_sheet, append_row
from .slides_service import create_presentation, add_title_slide
from .drive_service import find_file, rename_file, move_file, delete_file

__all__ = [
    "search_web",
    "summarise_search_results",
    "fetch_unread_summary",
    "write_email_summary",
    "build_markdown",
    "build_email_markdown",
    "search_messages_in_window",
    "mark_messages_read",
    "mark_messages_read_action",
    "mark_messages_unread",
    "archive_messages",
    "delete_messages",
    "apply_label",
    "send_email",
    "mark_inbox_unread",
    "search_messages_by_criteria",
    "fetch_full_message",
    "send_reply",
    "get_today_agenda",
    "get_tomorrow_agenda",
    "get_next_important_event",
    "get_events_between",
    "write_calendar_briefing",
    "build_daily_markdown",
    "create_event",
    "update_event",
    "delete_event",
    "list_tasks",
    "create_task",
    "update_task",
    "complete_task",
    "delete_task",
    "create_doc",
    "append_to_doc",
    "fetch_document",
    "search_docs",
    "render_document_text",
    "create_sheet",
    "append_row",
    "create_presentation",
    "add_title_slide",
    "find_file",
    "rename_file",
    "move_file",
    "delete_file",
]
